[package]

name = "lazysort"
version = "0.1.1"
authors = ["Ben Ashford"]
license = "MIT/Apache-2.0"
repository = "https://github.com/benashford/rust-lazysort"
description = "Lazy sorting for iterators"
readme = "README.md"

[dependencies]

rand = "^0.3"